WebApplication1/Models/ChangePasswordCustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class ChangePasswordCustomerViewModel
    {
        [Required]
        [StringLength(255, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [Display(Name = "New Password")]
        [DataType(DataType.Password)]
        public string NewPassword { get; set; }

        [Required]
        [Display(Name = "Confirm Password")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
    }
}

WebApplication1/Models/Customer.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class Customer
    {
        public int CustomerID { get; set; }

        [Required, MaxLength(50, ErrorMessage = "Please do not exceed 50 characters")]
        [Display(Name = "Name")]
        public string CustomerName { get; set; }

        [MaxLength(50, ErrorMessage = "Please do not exceed 50 characters")]
        [Display(Name = "Country")]
        public string Nationality { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Date of Birth")]
        public DateTime BirthDate { get; set; }

        [MaxLength(50, ErrorMessage = "Please do not exceed 50 characters")]
        public string TelNo { get; set; }


        [Required, MaxLength(50, ErrorMessage = "Please do not exceed 50 characters")]
        [Display(Name = "Email Address")]
        [EmailAddress]
        [ValidateEmail]
        public string EmailAddr { get; set; }


        [MaxLength(255, ErrorMessage = "Please do not exceed 255 characters")]
        [DataType(DataType.Password)]
        public string Password { get; set; }


    }
}

WebApplication1/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

    }
}

WebApplication1/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using WebApplication1.DAL;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity;
using System.Linq.Expressions;

namespace WebApplication1.Controllers
{
    public class BookingController : Controller
    {
        private BookingDAL bookingContext = new BookingDAL();
        // GET: BookingController
        public ActionResult Index()
        {
            BookingViewModel book = new BookingViewModel();
            book.list = bookingContext.GetFlightScheduleByStatus("Opened");

            return View(book);
        }

        public ActionResult ResultPage()
        {
            
            return View();
        }

        public ActionResult BookTickets(int? id)
        {
            
            if (id != null)
            {
                
                
                HttpContext.Session.SetString("ScheduleID", Convert.ToString(id));
                
                ViewData["ClassList"] = GetClass();
                
            }
            
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BookTickets(Booking booking, IFormCollection formData)
        {

            ViewData["ClassList"] = GetClass();

            if (ModelState.IsValid)
            {
                ViewData["ShowResult"] = true;
                decimal price = 0;
                //Add staff record to database
                int id = Convert.ToInt32(HttpContext.Session.GetString("Id"));
                int schedule = Convert.ToInt32(HttpContext.Session.GetString("ScheduleID"));
                string seatclass = formData["SeatClass"].ToString();
                HttpContext.Session.SetString("SeatClass", seatclass);
                List<decimal> pricelist = new List<decimal>();
                pricelist = bookingContext.GetPrice(schedule);
                if (seatclass == "Economy")
                {
                     price = pricelist[0];
                }
                else
                {
                     price = pricelist[1];
                }
                bookingContext.Add(booking, id, schedule, price);
                TempData["Price"] = Convert.ToString(price);
                TempData["Id"] = Convert.ToString(schedule);
                TempData["Seat"] = Convert.ToString(seatclass);
                
                return RedirectToAction("ResultPage");
            }
            else
            {
                return View();
            }
        }

        private List<SelectListItem> GetClass()
        {
            List<SelectListItem> classtier = new List<SelectListItem>();

            classtier.Add(new SelectListItem
            {
                Value = "Economy",
                Text = "Economy"
            });
            classtier.Add(new SelectListItem
            {
                Value ="Business",
                Text = "Business"
            });
           
            return classtier;
        }

        // GET: BookingController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BookingController/Create
        public ActionResult Booking()
        {
            return View();
        }

   

        // GET: BookingController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BookingController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BookingController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BookingController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using WebApplication1.DAL;
using WebApplication1.Models;


namespace WebApplication1.Controllers
{
    public class CustomerController : Controller
    {
        private CustomerDAL customerContext = new CustomerDAL();
        public ActionResult Index()
        {
            return View();
        }

        public IActionResult ChangePasswordCustomer()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ChangePasswordCustomer(IFormCollection formData)
        {
            
            if (ModelState.IsValid)
            {
                string password = formData["NewPassword"].ToString();
                string cpassword = formData["ConfirmPassword"].ToString();
                int id = Convert.ToInt32(HttpContext.Session.GetString("Id"));
                if (password == cpassword)
                {
                    customerContext.UpdatePassword(id, password);
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Passwordc"] = "Passwords do not match!";
                    return View();
                }
            }
            else
            {
                return View();
            }
        }

        


        public IActionResult BookTickets()
        {
            return View();  
        }

        public IActionResult ViewTickets()
        {
            return View();
        }

        // GET: Customer/Register
        public ActionResult Register()
        {
            return View();
        }

        // POST: Customer/Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(Customer customer, IFormCollection formData)
        {
            if (ModelState.IsValid)
            {
                //Add staff record to database
                customer.CustomerID = customerContext.Add(customer);
                string email = formData["EmailAddr"].ToString();
                string name = formData["CustomerName"].ToString();
                HttpContext.Session.SetString("Email", email);
                HttpContext.Session.SetString("Name", name);
                HttpContext.Session.SetString("Id", Convert.ToString(customerContext.GetId(email)));
                //Redirect user to Staff/Index view
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Message3"] = "Invalid Login Credentials!";
                //Input validation fails, return to the Create view
                //to display error message
                return View();
            }

        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(IFormCollection formData)
        {
            // Read inputs from textboxes
            // Email address converted to lowercase
            string email = formData["EmailAddr"].ToString();
            string password = formData["Password"].ToString();

            if (customerContext.IsPasswordCorrect(email, password) == false)
            {

                TempData["Message"] = "Invalid Login Credentials!";
                return View();
            }
            else
            {
                string name = customerContext.GetName(email);
                HttpContext.Session.SetString("Name", name);
                HttpContext.Session.SetString("Email", email);
                HttpContext.Session.SetString("Id", Convert.ToString(customerContext.GetId(email)));
                return RedirectToAction("Index");
            }
        }
    }
}

WebApplication1/Controllers/ViewTicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using WebApplication1.DAL;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;

namespace WebApplication1.Controllers
{
    public class ViewTicketsController : Controller
    {
        private BookingDAL bookingContext = new BookingDAL();
        // GET: ViewTicketsController
        public ActionResult Index()
        {

            ViewTicketsViewModel book = new ViewTicketsViewModel();
            int id = Convert.ToInt32(HttpContext.Session.GetString("Id"));
            book.list = bookingContext.GetBookingDetailsByCustomerId(id);
            return View(book);
        }


         public ActionResult TicketDetails(int? id)
        {

           
            TicketDetailsViewModel ticket = new TicketDetailsViewModel();
            if (id != null)
            {
                ticket.bookinglist = bookingContext.GetBookingDetailsByBookingId(Convert.ToInt32(id));
                int id2 = bookingContext.GetScheduleId(id.Value);
                ticket.flightlist = bookingContext.GetFlightScheduleByScheduleId(id2);
            }
            
            return View(ticket);
        }

        // GET: ViewTicketsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ViewTicketsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ViewTicketsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ViewTicketsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ViewTicketsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ViewTicketsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ViewTicketsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/Views/Customer/ChangePasswordCustomer.cshtml
@model WebApplication1.Models.ChangePasswordCustomerViewModel

@{
    ViewData["Title"] = "ChangePasswordCustomer";
    Layout = "~/Views/Customer/_CustomerNav.cshtml";
}

<h1>Change Password</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ChangePasswordCustomer">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NewPassword" class="control-label"></label>
                <input asp-for="NewPassword" class="form-control" />
                <span asp-validation-for="NewPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="control-label"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Confirm" class="btn btn-primary" />
            </div>
            <span style="color:red;">@TempData["Passwordc"]</span>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/Customer/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Customer/_CustomerNav.cshtml";
    var name = Context.Session.GetString("Name");

}

<h1 style="font-family: 'Pangolin', cursive">Welcome, @name!</h1>

WebApplication1/Views/Customer/Login.cshtml
 @model WebApplication1.Models.Customer

@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="EmailAddr" class="control-label"></label>
                <input asp-for="EmailAddr" class="form-control" />
                <span asp-validation-for="EmailAddr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
            <span style="color:red;">@TempData["Message"]</span>
        </form>
    </div>
</div>

<div>
    <p>Not a member yet? Register <a asp-area="" asp-controller="Customer" asp-action="Register">here</a></p>
    <a asp-controller="Home" asp-action="Index">Back to Home</a>
</div>

WebApplication1/Views/Customer/Register.cshtml
@model WebApplication1.Models.Customer

@{
    ViewData["Title"] = "Register";
}

<h1>Register with us!</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nationality" class="control-label"></label>
                <input asp-for="Nationality" class="form-control" />
                <span asp-validation-for="Nationality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TelNo" class="control-label"></label>
                <input asp-for="TelNo" class="form-control" />
                <span asp-validation-for="TelNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddr" class="control-label"></label>
                <input asp-for="EmailAddr" class="form-control" />
                <span asp-validation-for="EmailAddr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Register" class="btn btn-primary" />
            </div>
            
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index">Back to home</a>
</div>

WebApplication1/Views/Customer/_CustomerNav.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css2?family=Pangolin&display=swap" rel="stylesheet">
 
</head>
<body>
    <script>document.body.className += ' fade-out';</script>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand word" asp-area="" asp-controller="Customer" asp-action="Index">Lion City Airlines</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item list">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item list">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="ChangePasswordCustomer">Change Password</a>
                        </li>
                        <li class="nav-item list">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Index">Book Tickets</a>
                        </li>
                        <li class="nav-item list">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ViewTickets" asp-action="Index">View Tickets</a>
                        </li>
                        <li class="nav-item" style="background-color:khaki">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LogOut">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <script>$(function () {
            $('body').removeClass('fade-out');
        });</script>

</body>
</html>