WebApplication1/Models/ChangePasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

WebApplication1/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

    }
}

WebApplication1/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication1.DAL;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class AdminController : Controller
    {
        private AdminDAL adminContext = new AdminDAL();

        // GET: Project/Edit/5
        public ActionResult AddAirCraft()
        {

            return View();
        }

        // POST: Project/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAirCraft(AirCraftViewModel val)
        {


            if (ModelState.IsValid)
            {
                //Update staff record to database

                adminContext.AddAircraft(val);
                return RedirectToAction("ViewAirCrafts");


            }

            return RedirectToAction("AddAirCraft");
        }
        public IActionResult AircraftMaintenanceFilter()
        {
            List<AirCraftViewModel> detailslist = adminContext.GetAllAircraft();
            return View(detailslist);
        }
        public IActionResult ChangePassword()
        {
            return View("ChangePassword");
        }
        public IActionResult Index()
        {
            // Stop accessing the action if not logged in
            // or account not in the "Staff" role

            List<AircraftScheduleViewModel> detailslist = adminContext.GetAllAircraftSchedule();
            return View(detailslist);
        }
       

        public ActionResult StaffLogIn()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        //This function is called when your submit button is clicked 
        public ActionResult Login(IFormCollection formData)
        {
            //validate pass and user name 
            String username = formData["EmailAddr"].ToString();
            String password = formData["Password"].ToString();
            // username is "abcd@lionnet.com" password is "p@ssw0rd" 
            // boolean expression 
            // (variable/number) ** (variable/number) --> boolean operator --> <= < > >= == != 
            // x == 5 
            // when you want combine 2 boolean expresion 
            // && || 

            if (username == "abcd@lionet.com" && password == "p@ssw0rd")
            {
                // then you set the session variable httpContext.Session.setString("Role") = ""'
                // redirect to staffHomePage 
                // This is to set the session variable with the key called role to be "Staff"
                HttpContext.Session.SetString("Role", "Staff");
                //Reason why redirect to index funciton is because index funciton will take care of redirecting to home or staff view page
                return Redirect("Index");
            }
            else
            {
                // if i enter the wrong password 
                TempData["message"] = "Wrong email / password";
            }
            //Delete mext 2 line when you submit your code 
            // uncomment the next line that returns View("...");
            //HttpContext.Session.SetString("Role", "Staff");
            //return Redirect("Index");
            return View("StaffLogIn");
        }


        public IActionResult UpdateStatus(string id)
        {
            adminContext.UpdateStatus(id);
            List<AirCraftViewModel> detailslist = adminContext.GetAllAircraft();
            return View("AircraftMaintenanceFilter",detailslist);
        }
        public IActionResult ViewAirCrafts()
        {
            List<AircraftScheduleViewModel> aircraft = adminContext.GetAllAircraftSchedule();
            return View(aircraft);
        }

        // FlightSchedule
        public ActionResult AddFlightSchedule()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddFlightSchedule(FlightScheduleViewModel val)
        {

            if (ModelState.IsValid)
            {
                //Update staff record to database

                adminContext.AddFlightSchedule(val);
                return RedirectToAction("ViewSchedule");


            }

            return RedirectToAction("AddFlightSchedule");
        }
        public IActionResult ViewSchedule()
        {
            List<FlightScheduleViewModel> sched = adminContext.ViewFlightSchedule();
            return View(sched);
        }
        public ActionResult UpdateFlightSchedule()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateFlightSchedule(FlightScheduleViewModel val)
        {

            if (ModelState.IsValid)
            {
                //Update staff record to database

                adminContext.UpdateFlightSchedule(val);
                return RedirectToAction("ViewSchedule");


            }

            return RedirectToAction("UpdateFlightSchedule");
        }

        // FlightRoutes
        public ActionResult AddFlightRoute()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddFlightRoute(FlightRouteViewModel val)
        {

            if (ModelState.IsValid)
            {
                //Update staff record to database
                adminContext.AddRoute(val);
                return RedirectToAction("ViewRoutes");
            }
            return RedirectToAction("AddFlightRoute");
        }
        public IActionResult ViewRoutes()
        {
            List<FlightRouteViewModel> routes = adminContext.ViewRoutes();
            return View(routes);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteFlightRoute(FlightRouteViewModel val)
        {

            if (ModelState.IsValid)
            {
                //Update staff record to database
                adminContext.DeleteRoute(val);
                return RedirectToAction("ViewRoutes");
            }
            return RedirectToAction("DeleteFlightRoute");
        }

        public ActionResult AssignPilot(int ScheduleID, int StaffID)
        {
            FlightCrew flightCrew = new FlightCrew
            {
                ScheduleID = ScheduleID,
                StaffID = StaffID
            };
            List<SelectListItem> Roles = new List<SelectListItem>();
            Roles.Add(new SelectListItem { Value = "Flight Captain", Text = "Flight Captain" });
            Roles.Add(new SelectListItem { Value = "Second Pilot", Text = "Second Pilot" });
            ViewData["Roles"] = Roles;
            return View(flightCrew);
        }

        
        /*[HttpPost]
        public ActionResult AssignPilot(FlightCrew flightCrew)
        {
            adminContext.checkAssignment(flightCrew.Role, flightCrew.ScheduleID);
            return View();
        } */
        
        
        public ActionResult CreatePersonnel()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreatePersonnel(Staff staff)
        {
            if (ModelState.IsValid)
            {
                adminContext.AddStaff(staff);
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult ViewStaff()
        {
            List<StaffViewModel> staffList = adminContext.getAllStaffWithRoles();
            // go into database get all the staffs with their roles. 
            return View(staffList);
        }

        public ActionResult ViewFlightSchedule()
        {
            // How do i get the list of flight schedules 
            // i need to call staffDAL funciton (getAvaliableFlightSchedules)
            // in order to call a function from another file /class 
            // i need the object for that class. 
            // here the object is called staffContext

            List<FlightScheduleViewModel> FlightScheduleList = adminContext.getAvaliableFlightSchedules();
            return View(FlightScheduleList);
        }

        public ActionResult ViewAvailablePilots(int ScheduleID)
        {
            List<Staff> avaliablePliots = adminContext.GetAvaliablePilotStaff();
            TempData["ScheduleID"] = ScheduleID;
            return View(avaliablePliots);
        }
    }

}

WebApplication1/Views/Admin/AddFlightRoute.cshtml
@model WebApplication1.Models.FlightRouteViewModel

@{
    ViewData["Title"] = "AddFlightRoute";
    Layout = "~/Views/Admin/_AdminNav.cshtml";
}

<h1>Add Flight Route</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddFlightRoute">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DepartureCity" class="control-label"></label>
                <input asp-for="DepartureCity" class="form-control" />
                <span asp-validation-for="DepartureCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartureCountry" class="control-label"></label>
                <input asp-for="DepartureCountry" class="form-control" />
                <span asp-validation-for="DepartureCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArrivalCity" class="control-label"></label>
                <input asp-for="ArrivalCity" class="form-control" />
                <span asp-validation-for="ArrivalCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArrivalCountry" class="control-label"></label>
                <input asp-for="ArrivalCountry" class="form-control" />
                <span asp-validation-for="ArrivalCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlightDuration" class="control-label"></label>
                <input asp-for="FlightDuration" class="form-control" />
                <span asp-validation-for="FlightDuration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ViewRoutes">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/Admin/AddFlightSchedule.cshtml
@model WebApplication1.Models.FlightScheduleViewModel

@{
    ViewData["Title"] = "AddFlightSchedule";
    Layout = "~/Views/Admin/_AdminNav.cshtml";
}

<h1>Add Flight to Schedule</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddFlightSchedule">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ScheduleId" class="control-label"></label>
                <input asp-for="ScheduleId" class="form-control" />
                <span asp-validation-for="ScheduleId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RouteId" class="control-label"></label>
                <input asp-for="RouteId" class="form-control" />
                <span asp-validation-for="RouteId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AircraftId" class="control-label"></label>
                <input asp-for="AircraftId" class="form-control" />
                <span asp-validation-for="AircraftId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlightNumber" class="control-label"></label>
                <input asp-for="FlightNumber" class="form-control" />
                <span asp-validation-for="FlightNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartureDateTime" class="control-label"></label>
                <input asp-for="DepartureDateTime" class="form-control" />
                <span asp-validation-for="DepartureDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArrivalDateTime" class="control-label"></label>
                <input asp-for="ArrivalDateTime" class="form-control" />
                <span asp-validation-for="ArrivalDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EconomyClassPrice" class="control-label"></label>
                <input asp-for="EconomyClassPrice" class="form-control" />
                <span asp-validation-for="EconomyClassPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BusinessClassPrice" class="control-label"></label>
                <input asp-for="BusinessClassPrice" class="form-control" />
                <span asp-validation-for="BusinessClassPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ViewSchedule">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Admin/_AdminNav.cshtml";
}

<h1>Index</h1>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    if (ViewBag.Message != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
            };
        </script>
    }
}
<head>
    <style>
        * {
            box-sizing: border-box;
        }

        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        /* Float four columns side by side */
        .column {
            float: left;
            width: 25%;
            padding: 0px 10px;
            margin-left: 70px;
        }

        /* Remove extra left and right margins, due to padding in columns */
        .row {
            margin: 0 -5px;
        }

            /* Clear floats after the columns */
            .row:after {
                content: "";
                display: table;
                clear: both;
            }

        /* Style the counter cards */
        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2); /* this adds the "card" effect */
            padding: 16px;
            height: 150px;
            text-align: center;
            background-color: #f1f1f1;
        }
        
    </style>
</head>
<body>
    <br /><br />
    <center>
        <div class="row">
            <div class="column">
                <div class="card">
                    <h3>Total Aircrafts</h3>
                    <h3>@ViewBag.c1</h3>
                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ViewAirCrafts">button</a>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <h3>Operational Aircrafts</h3>
                    <h3>@ViewBag.c2</h3>
                    
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <h3>Under Maintenance Aircrafts</h3>
                    <h3>@ViewBag.c3</h3>
                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="AircraftMaintenanceFilter">button</a>
                </div>
            </div>

        </div>
        <br />
        <div class="row">
            <div class="column">
                <div class="card">
                    <h3>Total Bookings</h3>
                    <h3>@ViewBag.c4</h3>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <h3>Total Customer</h3>
                    <h3>@ViewBag.c5</h3>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <h3>Total Flights</h3>
                    <h3>@ViewBag.c6</h3>
                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ViewSchedule">button</a>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="column">
                <div class="card">
                    <h3>Total Staff Members</h3>
                    <h3>@ViewBag.c7</h3>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <h3>Male Staff Members</h3>
                    <h3>@ViewBag.c8</h3>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <h3>Female Staff Members</h3>
                    <h3>@ViewBag.c9</h3>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <h3>Create Staff record</h3>
                    <h3>@ViewBag.c1</h3>
                    <a class="nav-link text-dark" asp-controller="Admin" asp-action="CreatePersonnel">button</a>
                </div>
            </div>

            <div class="column">
                <div class="card">
                    <h3>View All personnel and flight assigned</h3>
                    <h3>@ViewBag.c3</h3>
                    <a class="nav-link text-dark" asp-controller="Admin" asp-action="ViewStaff">button</a>
                </div>
            </div>

            <div class="column">
                <div class="card">
                    <h3>Assign Pilots and Attendents to flight</h3>
                    <h3>@ViewBag.c3</h3>
                    <a class="nav-link text-dark" asp-controller="Admin" asp-action="ViewFlightSchedule">Assign Crew</a>
                </div>
            </div>
        </div>
    </center>
</body>

WebApplication1/Views/Admin/Login.cshtml
@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Admin/_AdminNav.cshtml";
}

<h1>Login</h1>

WebApplication1/Views/Admin/StaffLogIn.cshtml
@model WebApplication1.Models.Staff

@{
    ViewData["Title"] = "StaffLogIn";
}

<h1>Login</h1>

<h4>Staff</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="EmailAddr" class="control-label"></label>
                <input asp-for="EmailAddr" class="form-control" />
                <span asp-validation-for="EmailAddr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
            <span style="color:red;">@TempData["Message"]</span>
        </form>
    </div>
</div>

WebApplication1/Views/Admin/UpdateFlightSchedule.cshtml
@model WebApplication1.Models.FlightScheduleViewModel

@{
    ViewData["Title"] = "UpdateFlightSchedule";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Update Flight Schedule</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateFlightSchedule">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ScheduleId" class="control-label"></label>
                <input asp-for="ScheduleId" class="form-control" />
                <span asp-validation-for="ScheduleId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RouteId" class="control-label"></label>
                <input asp-for="RouteId" class="form-control" />
                <span asp-validation-for="RouteId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AircraftId" class="control-label"></label>
                <input asp-for="AircraftId" class="form-control" />
                <span asp-validation-for="AircraftId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlightNumber" class="control-label"></label>
                <input asp-for="FlightNumber" class="form-control" />
                <span asp-validation-for="FlightNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartureDateTime" class="control-label"></label>
                <input asp-for="DepartureDateTime" class="form-control" />
                <span asp-validation-for="DepartureDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArrivalDateTime" class="control-label"></label>
                <input asp-for="ArrivalDateTime" class="form-control" />
                <span asp-validation-for="ArrivalDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EconomyClassPrice" class="control-label"></label>
                <input asp-for="EconomyClassPrice" class="form-control" />
                <span asp-validation-for="EconomyClassPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BusinessClassPrice" class="control-label"></label>
                <input asp-for="BusinessClassPrice" class="form-control" />
                <span asp-validation-for="BusinessClassPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/Admin/UpdateStaffStatus.cshtml
@model WebApplication1.Models.Staff
@{
    ViewData["Title"] = "UpdateStaffStatus";
    Layout = "~/Views/Staff/StaffNav.cshtml";
}

<h1>UpdateStaffStatus</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="updateStatus">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StaffID" class="control-label"></label>
                <input asp-for="StaffID" class="form-control" />
                <span asp-validation-for="StaffID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StaffName" class="control-label"></label>
                <input asp-for="StaffName" class="form-control" />
                <span asp-validation-for="StaffName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateEmployed" class="control-label"></label>
                <input asp-for="DateEmployed" class="form-control" />
                <span asp-validation-for="DateEmployed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vocation" class="control-label"></label>
                <input asp-for="Vocation" class="form-control" />
                <span asp-validation-for="Vocation" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="EmailAddr" class="control-label"></label>
                <input asp-for="EmailAddr" class="form-control" />
                <span asp-validation-for="EmailAddr" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>



            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApplication1/Views/Admin/_AdminNav.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">Admin Homepage</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="AddAircraft">Add Aircraft</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ViewAirCrafts">View All</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ChangePassword">Change Password</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="AircraftMaintenanceFilter">Maintenance</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ViewRoutes">Flight Routes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ViewSchedule">Flight Schedule</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="CreatePersonnel">Create Personnel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ViewStaff">View Staff</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>